[package]
description = "trustnote rust implmentation"
name = "trustnote"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT"

[dependencies]
log = "0.4"
may = "0.3"
url = "1.7"
tungstenite = "0.5"

[dependencies.rusqlite]
version = "0.13"
features = ["bundled"]
